### ISSUE TITLE
Crash gameworld tick

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#251]
```

[19-06-08 14:21:20][game]: kill killer='1:Chillingo.*' victim='7:ζеρτ☯' weapon=-2 special=0
[19-06-08 14:21:26][debug]: character die ID: 3 Name: MLG_PRO.*
[19-06-08 14:21:26][game]: kill killer='6:✔atlantiz☯' victim='3:MLG_PRO.*' weapon=-2 special=0
[19-06-08 14:22:50][chat]: *** ✔atlantiz☯ finished in: 1 minute(s) 21.26 second(s)
[19-06-08 14:22:50][chat]: *** New record: 1 minute(s) 16.58 second(s) better.
[19-06-08 14:22:50][debug]: score search name '✔atlantiz☯'
[New Thread 0x7fffeee53700 (LWP 28722)]
[Thread 0x7fffeee53700 (LWP 28722) exited]
[19-06-08 14:22:51][chat]: *** ζеρτ☯ finished in: 1 minute(s) 21.14 second(s)
[19-06-08 14:22:51][chat]: *** New record: 58.96 second(s) better.
[19-06-08 14:22:51][debug]: score search name 'ζеρτ☯'
[New Thread 0x7fffeee53700 (LWP 28723)]
[Thread 0x7fffeee53700 (LWP 28723) exited]

Program received signal SIGSEGV, Segmentation fault.
0x000000000046b35c in CGameWorld::Tick (this=0x7ffff507c3c0) at src/game/server/gameworld.cpp:296
296                                     pEnt->Tick();
(gdb) bt
#0  0x000000000046b35c in CGameWorld::Tick (this=0x7ffff507c3c0) at src/game/server/gameworld.cpp:296
#1  0x00000000004b0822 in CGameContext::OnTick (this=0x7ffff506e010) at src/game/server/gamecontext.cpp:1188
#2  0x0000000000443f94 in CServer::Run (this=0x7ffff58a0010) at src/engine/server/server.cpp:2108
#3  0x00000000004462d1 in main (argc=2, argv=0x7fffffffde48) at src/engine/server/server.cpp:2629
```

**Comment by ChillerDragon** [comment]
```

[19-06-23 12:39:27][server]: ':(' -> ':('
[19-06-23 12:39:27][server]: player has entered the game. ClientID=7 addr=XXXXXX
[19-06-23 12:39:27][debug]: score search name ':('
[New Thread 0x7fffeee53700 (LWP 7326)]
[19-06-23 12:39:27][chat]: *** ':(' entered and joined the game
[19-06-23 12:39:27][game]: team_join player='7::(' team=0
[Thread 0x7fffeee53700 (LWP 7326) exited]
[19-06-23 12:39:28][DDNet]: 7 using Custom Client 12010
[19-06-23 12:39:30][chat-command]: 7 used /timeout XXX
[19-06-23 12:39:40][chat-command]: 5 used /timeout XXX
[19-06-23 12:40:04][chat]: *** :( finished in: 0 minute(s) 25.56 second(s)
[19-06-23 12:40:04][chat]: *** New record: 2 minute(s) 10.60 second(s) better.
[19-06-23 12:40:04][debug]: score search name ':('
[New Thread 0x7fffeee53700 (LWP 7329)]
[Thread 0x7fffeee53700 (LWP 7329) exited]
[19-06-23 12:40:09][chat-command]: 5 used /emote happy 999999
[19-06-23 12:40:31][chat]: *** :) finished in: 1 minute(s) 10.88 second(s)
[19-06-23 12:40:31][debug]: score search name ':)'
[New Thread 0x7fffeee53700 (LWP 7374)]
[Thread 0x7fffeee53700 (LWP 7374) exited]

Program received signal SIGSEGV, Segmentation fault.
0x000000000046b35c in CGameWorld::Tick (this=0x7ffff507c3c0) at src/game/server/gameworld.cpp:296
296                                     pEnt->Tick();
(gdb) bt
#0  0x000000000046b35c in CGameWorld::Tick (this=0x7ffff507c3c0) at src/game/server/gameworld.cpp:296
#1  0x00000000004b0822 in CGameContext::OnTick (this=0x7ffff506e010) at src/game/server/gamecontext.cpp:1188
#2  0x0000000000443f94 in CServer::Run (this=0x7ffff58a0010) at src/engine/server/server.cpp:2108
#3  0x00000000004462d1 in main (argc=2, argv=0x7fffffffde48) at src/engine/server/server.cpp:2629
(gdb)

```

**Comment by ChillerDragon** [comment]
Might be a flag nullptr that was fixed in the clang tidy commits
