### ISSUE TITLE
Crash on drop loot

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#259]
```
[19-07-19 13:31:22][debug]: character die ID: 13 Name: <bot>

Thread 1 "chillblock_srv_" received signal SIGSEGV, Segmentation fault.
0x0000555555616a18 in CCharacter::DropWeapon (this=0x555555bf7948 <ms_PoolDataCCharacter+1739400>, WeaponID=1) at src/game/server/entities/character.cpp:6134
6134    m_pPlayer->m_vWeaponLimit[WeaponID][0]->Reset();
(gdb) bt
#0  0x0000555555616a18 in CCharacter::DropWeapon (this=0x555555bf7948 <ms_PoolDataCCharacter+1739400>, WeaponID=1)
    at src/game/server/entities/character.cpp:6134
#1  0x0000555555616262 in CCharacter::DropLoot (this=0x555555bf7948 <ms_PoolDataCCharacter+1739400>) at src/game/server/entities/character.cpp:6056
#2  0x000055555561a1ed in CCharacter::DDPP_DIE (this=0x555555bf7948 <ms_PoolDataCCharacter+1739400>, Killer=13, Weapon=-2, fngscore=false)
    at src/game/server/entities/character.cpp:6942
#3  0x0000555555602ba6 in CCharacter::Die (this=0x555555bf7948 <ms_PoolDataCCharacter+1739400>, Killer=13, Weapon=-2, fngscore=false)
    at src/game/server/entities/character.cpp:2204
#4  0x00005555555e5625 in CCharacter::DummyTick (this=0x555555bf7948 <ms_PoolDataCCharacter+1739400>)
    at src/game/server/entities/character_dummymodes.cpp:7152
#5  0x0000555555601978 in CCharacter::Tick (this=0x555555bf7948 <ms_PoolDataCCharacter+1739400>) at src/game/server/entities/character.cpp:1987
#6  0x000055555562d929 in CGameWorld::Tick (this=0x7ffff7fc73c0) at src/game/server/gameworld.cpp:296
#7  0x000055555567d5a8 in CGameContext::OnTick (this=0x7ffff7fb9010) at src/game/server/gamecontext.cpp:1242
#8  0x00005555555af6a7 in CServer::Run (this=0x7ffff4968010) at src/engine/server/server.cpp:2124
#9  0x00005555555b1a66 in main (argc=2, argv=0x7fffffffe038) at src/engine/server/server.cpp:2649
```

**Comment by ChillerDragon** [comment]
Possible fix
https://github.com/DDNetPP/DDNetPP/commit/9d419da493f703d0d080f076995261e5c9a63e9d

Related issue
https://github.com/DDNetPP/DDNetPP/issues/317
