### ISSUE TITLE
Crash on jail code

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#283]
```
[19-08-31 00:25:40][chat-command]: 4 used /cmdlist
[...]
[19-08-31 00:26:18][chat-command]: 4 used /jail
[19-08-31 00:26:19][chat-command]: 4 used /jail leave
[19-08-31 00:26:34][chat-command]: 4 used /jail open
[19-08-31 00:26:44][chat-command]: 4 used /jail code 0
[19-08-31 00:26:48][chat-command]: 4 used /jail code 1PA

Thread 1 "BlmapChill_srv_" received signal SIGSEGV, Segmentation fault.
0x000055555565a2f4 in CGameContext::ConJail (pResult=0x7fffffff0820, pUserData=0x7ffff7fb6010) at src/game/server/ddracechat.cpp:7595
warning: Source file is more recent than executable.
7595   CGameContext *pSelf = (CGameContext *)pUserData;
(gdb) bt
#0  0x000055555565a2f4 in CGameContext::ConJail (pResult=0x7fffffff0820, pUserData=0x7ffff7fb6010) at src/game/server/ddracechat.cpp:7595
#1  0x000055555558b070 in CConsole::ExecuteLineStroked (this=0x555556c32e30, Stroke=1, pStr=0x7ffff5b01ac6 "jail code 2323232", ClientID=4)
    at src/engine/shared/console.cpp:414
#2  0x000055555558b2f9 in CConsole::ExecuteLine (this=0x555556c32e30, pStr=0x7ffff5b01ac6 "jail code 2323232", ClientID=4)
    at src/engine/shared/console.cpp:467
#3  0x0000555555697369 in CGameContext::OnMessage (this=0x7ffff7fb6010, MsgID=17, pUnpacker=0x7fffffffd2c0, ClientID=4)
    at src/game/server/gamecontext.cpp:7452
#4  0x00005555555ae1b9 in CServer::ProcessClientPacket (this=0x7ffff4968010, pPacket=0x7fffffffdcc0) at src/engine/server/server.cpp:1665
#5  0x00005555555aed02 in CServer::PumpNetwork (this=0x7ffff4968010) at src/engine/server/server.cpp:1848
#6  0x00005555555afe59 in CServer::Run (this=0x7ffff4968010) at src/engine/server/server.cpp:2139
#7  0x00005555555b218c in main (argc=2, argv=0x7fffffffe038) at src/engine/server/server.cpp:2648

```

**Comment by ChillerDragon** [comment]
User was not jailed logged in with police2 account.

**Comment by ChillerDragon** [comment]
```
[19-09-01 17:26:44][chat-command]: 2 used /jail code 1

Thread 1 "BlmapChill_srv_" received signal SIGSEGV, Segmentation fault.
0x00005555556b2e5c in CGameContext::ConJail (pResult=0x7fffffff0810, pUserData=0x7ffff7fb5010) at src/game/server/ddracechat.cpp:7481
7481    if (!pSelf->m_apPlayers[pResult->GetInteger(1)])
(gdb) bt
#0  0x00005555556b2e5c in CGameContext::ConJail (pResult=0x7fffffff0810, pUserData=0x7ffff7fb5010) at src/game/server/ddracechat.cpp:7481
#1  0x0000555555584238 in CConsole::ExecuteLineStroked (this=0x555556c37e30, Stroke=1, pStr=0x7ffff5b01ac6 "jail code 10898987987675", ClientID=2)
    at src/engine/shared/console.cpp:419
#2  0x00005555555844c1 in CConsole::ExecuteLine (this=0x555556c37e30, pStr=0x7ffff5b01ac6 "jail code 10898987987675", ClientID=2)
    at src/engine/shared/console.cpp:472
#3  0x00005555556075eb in CGameContext::OnMessage (this=0x7ffff7fb5010, MsgID=17, pUnpacker=0x7fffffffd2c0, ClientID=2)
    at src/game/server/gamecontext.cpp:7611
#4  0x00005555555ae561 in CServer::ProcessClientPacket (this=0x7ffff4968010, pPacket=0x7fffffffdcc0) at src/engine/server/server.cpp:1675
#5  0x00005555555aeff6 in CServer::PumpNetwork (this=0x7ffff4968010) at src/engine/server/server.cpp:1863
#6  0x00005555555b014d in CServer::Run (this=0x7ffff4968010) at src/engine/server/server.cpp:2154
#7  0x00005555555b24a2 in main (argc=2, argv=0x7fffffffe038) at src/engine/server/server.cpp:2663
```
