### ISSUE TITLE
Killingspree recursive crashbug

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#295]
```
[19-09-12 17:46:37][chat-command]: 7 used /gift ~
[19-09-12 17:46:37][chat-command]: 24 used /AccountInfo b\@G#N
[19-09-12 17:46:37][chat-command]: 9 used /changepassword )df3I=|U_4yK|b%.~~t@.uaVwN,L]$B-(�POOB+/sUjdWmvSh
[19-09-12 17:46:37][console]: No such command: jail_hammer.
[19-09-12 17:46:37][chat-command]: 31 used /jail_hammer 'Raf
[19-09-12 17:46:37][chat-command]: 0 used /broadcast_srv (OSZ+'fz&lS0t?4-B5|
[19-09-12 17:46:37][chat-command]: 10 used /survival join
[19-09-12 17:46:37][debug]: character die ID: 20 Name: (25)ChillerDrag
[19-09-12 17:46:37][game]: kill killer='6:(14)ChillerDrag' victim='20:(25)ChillerDrag' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 11 Name: (2)ChillerDrago
[19-09-12 17:46:37][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (8 Kills)
[19-09-12 17:46:37][debug]: character die ID: 11 Name: (2)ChillerDrago
[19-09-12 17:46:37][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (8 Kills)
[19-09-12 17:46:37][debug]: character die ID: 32 Name: (11)ChillerDrag
[19-09-12 17:46:37][game]: kill killer='11:(2)ChillerDrago' victim='32:(11)ChillerDrag' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 1 Name: (12)ChillerDrag
[19-09-12 17:46:37][chat]: *** '(2)ChillerDrago' is on a killing spree with 10 kills!
[19-09-12 17:46:37][game]: kill killer='11:(2)ChillerDrago' victim='1:(12)ChillerDrag' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 9 Name: (17)ChillerDrag
[19-09-12 17:46:37][game]: kill killer='11:(2)ChillerDrago' victim='9:(17)ChillerDrag' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 10 Name: (23)ChillerDrag
[19-09-12 17:46:37][game]: kill killer='11:(2)ChillerDrago' victim='10:(23)ChillerDrag' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 11 Name: (2)ChillerDrago
[19-09-12 17:46:37][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (12 Kills)
[19-09-12 17:46:37][debug]: character die ID: 20 Name: (25)ChillerDrag
[19-09-12 17:46:37][game]: kill killer='11:(2)ChillerDrago' victim='20:(25)ChillerDrag' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 31 Name: (6)ChillerDrago
[19-09-12 17:46:37][game]: kill killer='11:(2)ChillerDrago' victim='31:(6)ChillerDrago' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 6 Name: (14)ChillerDrag
[19-09-12 17:46:37][chat]: *** '(2)ChillerDrago' is on a killing spree with 15 kills!
[19-09-12 17:46:37][game]: kill killer='11:(2)ChillerDrago' victim='6:(14)ChillerDrag' weapon=3 special=0
[19-09-12 17:46:37][debug]: character die ID: 11 Name: (2)ChillerDrago
[19-09-12 17:46:37][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (15 Kills)
[19-09-12 17:46:37][debug]: character die ID: 11 Name: (2)ChillerDrago
[19-09-12 17:46:37][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (15 Kills)
[...]
[19-09-12 17:46:38][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (16 Kills)
[19-09-12 17:46:38][debug]: character die ID: 11 Name: (2)ChillerDrago
[19-09-12 17:46:38][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (16 Kills)
[19-09-12 17:46:38][debug]: character die ID: 11 Name: (2)ChillerDrago
[19-09-12 17:46:38][chat]: *** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (16 Kills)
[19-09-12 17:46:38][debug]: character die ID: 11 Name: (2)ChillerDrago

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ae7a0a in _IO_vfprintf_internal (s=s@entry=0x7fffff7ff110, format=format@entry=0x55555577e514 "[%s][%s]: ", ap=ap@entry=0x7fffff7ff2a0) at vfprintf.c:1239
1239	vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7ae7a0a in _IO_vfprintf_internal (s=s@entry=0x7fffff7ff110, format=format@entry=0x55555577e514 "[%s][%s]: ", ap=ap@entry=0x7fffff7ff2a0) at vfprintf.c:1239
#1  0x00007ffff7b107a0 in _IO_vsnprintf (string=0x55555585a8c0 <log_queue+45056> "", maxlen=<optimized out>, format=0x55555577e514 "[%s][%s]: ", args=0x7fffff7ff2a0) at vsnprintf.c:114
#2  0x00005555555a35af in str_format (buffer=0x55555585a8c0 <log_queue+45056> "", buffer_size=4096, format=0x55555577e514 "[%s][%s]: ") at src/base/system.c:1981
#3  0x00005555555a0562 in dbg_msg (sys=0x555555784344 "chat", fmt=0x555555775067 "%s") at src/base/system.c:219
#4  0x000055555558410b in CConsole::Print (this=0x555556a54790, Level=2, pFrom=0x555555784344 "chat", pStr=0x7fffff800a70 "*** '(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (16 Kills)", 
    Highlighted=false) at src/engine/shared/console.cpp:248
#5  0x00005555555f02e3 in CGameContext::SendChat (this=0x7ffff5054010, ChatterClientID=-1, Team=-2, pText=0x7fffff800c00 "'(2)ChillerDrago's killing spree was ended by '(11)ChillerDrag' (16 Kills)", 
    SpamProtectionClientID=-1, ToClientID=-1) at src/game/server/gamecontext.cpp:864
#6  0x000055555568b536 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7549
#7  0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#8  0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#9  0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#10 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#11 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#12 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#13 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#14 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#15 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#16 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#17 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#18 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#19 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#20 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#21 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#22 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#23 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#24 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#25 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#26 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#27 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#28 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#29 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#30 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#31 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#32 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#33 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#34 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#35 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#36 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#37 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#38 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#39 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#40 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#41 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#42 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#43 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#44 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#45 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=130827680701) at src/game/server/gamecontext.cpp:689
#46 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#47 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#48 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#49 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
[...]
#16970 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=137405399039) at src/game/server/gamecontext.cpp:689
#16971 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#16972 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:6718
#16973 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=11, Weapon=3, fngscore=false) at src/game/server/entities/character.cpp:2199
#16974 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=11, Weapon=3) at src/game/server/entities/character.cpp:2409
#16975 0x00005555555ef92e in CGameContext::CreateExplosion (this=0x7ffff5054010, Pos=..., Owner=11, Weapon=3, NoDamage=false, ActivatedTeam=0, Mask=137405399039) at src/game/server/gamecontext.cpp:689
#16976 0x000055555568b5c7 in CCharacter::KillingSpree (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32) at src/game/server/entities/character.cpp:7550
#16977 0x0000555555687481 in CCharacter::DDPP_DIE (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=0, fngscore=false) at src/game/server/entities/character.cpp:6718
#16978 0x0000555555670b6c in CCharacter::Die (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Killer=32, Weapon=0, fngscore=false) at src/game/server/entities/character.cpp:2199
#16979 0x0000555555671bac in CCharacter::TakeDamage (this=0x555555b30318 <ms_PoolDataCCharacter+1471800>, Force=..., Dmg=3, From=32, Weapon=0) at src/game/server/entities/character.cpp:2409
#16980 0x000055555566bced in CCharacter::FireWeapon (this=0x555555dde2e0 <ms_PoolDataCCharacter+4281600>, Bot=false) at src/game/server/entities/character.cpp:1148
#16981 0x000055555566ee50 in CCharacter::OnDirectInput (this=0x555555dde2e0 <ms_PoolDataCCharacter+4281600>, pNewInput=0x7ffff5bb4a58) at src/game/server/entities/character.cpp:1836
#16982 0x00005555555d7b39 in CPlayer::OnDirectInput (this=0x5555558babc0 <ms_PoolDataCPlayer+368640>, NewInput=0x7ffff5bb4a58) at src/game/server/player.cpp:984
#16983 0x00005555555f2e99 in CGameContext::OnClientDirectInput (this=0x7ffff5054010, ClientID=32, pInput=0x7ffff5bb4a58) at src/game/server/gamecontext.cpp:1496
#16984 0x00005555555adc56 in CServer::ProcessClientPacket (this=0x7ffff5889010, pPacket=0x7fffffffdd20) at src/engine/server/server.cpp:1471
#16985 0x00005555555af84e in CServer::PumpNetwork (this=0x7ffff5889010) at src/engine/server/server.cpp:1863
#16986 0x00005555555b09ea in CServer::Run (this=0x7ffff5889010) at src/engine/server/server.cpp:2157
#16987 0x00005555555b2d64 in main (argc=2, argv=0x7fffffffe098) at src/engine/server/server.cpp:2666
```

**Comment by ChillerDragon** [comment]
The killingspree explosion should not deal damage anyways. But still I don't understand how it started the recursion. But it is most likley fixed by this commit https://github.com/DDNetPP/DDNetPP/commit/df08218039357495231ea8bf538554bdaccb8764

**Comment by ChillerDragon** [comment]
Five days of intensive stress testing and debugging and I could not reproduce it. So most likley fixed by https://github.com/DDNetPP/DDNetPP/commit/df08218039357495231ea8bf538554bdaccb8764.
