### ISSUE TITLE
Droploot crashbug in vmath.h

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#296]
```
[19-09-12 18:33:09][chat-command]: 36 used /survival joinf
[19-09-12 18:33:09][debug]: character die ID: 3 Name: (20)ChillerDrag
[19-09-12 18:33:09][game]: kill killer='3:(20)ChillerDrag' victim='3:(20)ChillerDrag' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 10 Name: (14)ChillerDrag
[19-09-12 18:33:09][game]: kill killer='10:(14)ChillerDrag' victim='10:(14)ChillerDrag' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 11 Name: (3)ChillerDrago
[19-09-12 18:33:09][game]: kill killer='11:(3)ChillerDrago' victim='11:(3)ChillerDrago' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 12 Name: (6)ChillerDrago
[19-09-12 18:33:09][game]: kill killer='12:(6)ChillerDrago' victim='12:(6)ChillerDrago' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 13 Name: (9)ChillerDrago
[19-09-12 18:33:09][game]: kill killer='13:(9)ChillerDrago' victim='13:(9)ChillerDrago' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 15 Name: (28)ChillerDrag
[19-09-12 18:33:09][game]: kill killer='15:(28)ChillerDrag' victim='15:(28)ChillerDrag' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 21 Name: (2)ChillerDrago
[19-09-12 18:33:09][game]: kill killer='21:(2)ChillerDrago' victim='21:(2)ChillerDrago' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 22 Name: (34)ChillerDrag
[19-09-12 18:33:09][game]: kill killer='22:(34)ChillerDrag' victim='22:(34)ChillerDrag' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 28 Name: (25)ChillerDrag
[19-09-12 18:33:09][game]: kill killer='28:(25)ChillerDrag' victim='28:(25)ChillerDrag' weapon=-3 special=0
[19-09-12 18:33:09][debug]: character die ID: 29 Name: (31)ChillerDrag
[19-09-12 18:33:09][game]: kill killer='29:(31)ChillerDrag' victim='29:(31)ChillerDrag' weapon=-3 special=0
[19-09-12 18:33:09][server]: client dropped. cid=22 addr=[0:0:0:0:0:0:0:1]:38567 reason=''
[19-09-12 18:33:09][debug]: character die ID: 22 Name: (34)ChillerDrag

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
0x00005555555c0814 in vector2_base<float>::operator= (this=0x555557b49e10, v=...) at src/base/vmath.h:34
34		const vector2_base &operator =(const vector2_base &v) { x = v.x; y = v.y; return *this; }
(gdb) bt
#0  0x00005555555c0814 in vector2_base<float>::operator= (this=0x555557b49e10, v=...) at src/base/vmath.h:34
#1  0x000055555563f736 in CDropPickup::CDropPickup (this=0x555557b49de0, pGameWorld=0x7ffff50623c0, Type=1, Lifetime=300, Owner=22, Direction=0, Force=1, ResponsibleTeam=0)
    at src/game/server/entities/drop_pickup.cpp:18
#2  0x00005555556838dd in CCharacter::DropArmor (this=0x555555c97850 <ms_PoolDataCCharacter+2943600>, amount=5) at src/game/server/entities/character.cpp:5876
#3  0x000055555568331b in CCharacter::DropLoot (this=0x555555c97850 <ms_PoolDataCCharacter+2943600>) at src/game/server/entities/character.cpp:5811
#4  0x00005555556874a7 in CCharacter::DDPP_DIE (this=0x555555c97850 <ms_PoolDataCCharacter+2943600>, Killer=22, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:6720
#5  0x0000555555670b6c in CCharacter::Die (this=0x555555c97850 <ms_PoolDataCCharacter+2943600>, Killer=22, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:2199
#6  0x00005555555d7e55 in CPlayer::KillCharacter (this=0x55555589e9c0 <ms_PoolDataCPlayer+253440>, Weapon=-3) at src/game/server/player.cpp:1034
#7  0x00005555555d75c3 in CPlayer::OnDisconnect (this=0x55555589e9c0 <ms_PoolDataCPlayer+253440>, pReason=0x7ffff66aba98 "", silent=false) at src/game/server/player.cpp:904
#8  0x00005555555f40c2 in CGameContext::OnClientDrop (this=0x7ffff5054010, ClientID=22, pReason=0x7ffff66aba98 "", silent=false) at src/game/server/gamecontext.cpp:1794
#9  0x00005555555ac54f in CServer::DelClientCallback (ClientID=22, pReason=0x7ffff66aba98 "", pUser=0x7ffff5889010) at src/engine/server/server.cpp:1156
#10 0x0000555555570e40 in CNetServer::Drop (this=0x7ffff65e9e18, ClientID=22, pReason=0x7ffff66aba98 "") at src/engine/shared/network_server.cpp:90
#11 0x0000555555570f77 in CNetServer::Update (this=0x7ffff65e9e18) at src/engine/shared/network_server.cpp:106
#12 0x00005555555af706 in CServer::PumpNetwork (this=0x7ffff5889010) at src/engine/server/server.cpp:1840
#13 0x00005555555b09ea in CServer::Run (this=0x7ffff5889010) at src/engine/server/server.cpp:2157
#14 0x00005555555b2d64 in main (argc=2, argv=0x7fffffffe098) at src/engine/server/server.cpp:2666
```

**Comment by ChillerDragon** [comment]
From the new debugging commit:

```
[19-09-14 17:48:04][game]: kill killer='24:(24)ChillerDrag' victim='24:(24)ChillerDrag' weapon=-3 special=0
[19-09-14 17:48:04][console]: No such command: )TPHf{Iyp:>:N,so��xfju}9-.
[19-09-14 17:48:04][chat-command]: 6 used /changepassword Jk!)ZD]N%[';)TPHf{Iyp:>:N,so��xfju}9-#e1%ER{]tl.CUQS%5�lT,5U.
[19-09-14 17:48:04][console]: No such command: !.
[19-09-14 17:48:04][console]: No such command: +M.
[19-09-14 17:48:04][chat-command]: 22 used /register %;! ?zP ;+M
[19-09-14 17:48:04][chat-command]: 20 used /register /CA }zr 2_.
[19-09-14 17:48:05][server]: client dropped. cid=7 addr=[0:0:0:0:0:0:0:1]:44784 reason=''
[19-09-14 17:48:05][debug]: character die ID: 7 Name: (7)ChillerDrago
[19-09-14 17:48:05][assert]: src/game/server/entities/drop_pickup.cpp(21): droppickup playerchar is null

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
dbg_break () at src/base/system.c:109
109		*((volatile unsigned*)0) = 0x0;
(gdb) bt
#0  dbg_break () at src/base/system.c:109
#1  0x00005555555a0210 in dbg_assert_imp (filename=0x55555578d130 "src/game/server/entities/drop_pickup.cpp", line=21, test=0, msg=0x55555578d159 "droppickup playerchar is null") at src/base/system.c:103
#2  0x000055555563e82f in CDropPickup::CDropPickup (this=0x555557a35c10, pGameWorld=0x7ffff50603c0, Type=1, Lifetime=300, Owner=7, Direction=-1, Force=0, ResponsibleTeam=0)
    at src/game/server/entities/drop_pickup.cpp:21
#3  0x0000555555682b2b in CCharacter::DropArmor (this=0x555555aaa878 <ms_PoolDataCCharacter+936600>, amount=2) at src/game/server/entities/character.cpp:5873
#4  0x0000555555682569 in CCharacter::DropLoot (this=0x555555aaa878 <ms_PoolDataCCharacter+936600>) at src/game/server/entities/character.cpp:5808
#5  0x00005555556866f5 in CCharacter::DDPP_DIE (this=0x555555aaa878 <ms_PoolDataCCharacter+936600>, Killer=7, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:6717
#6  0x000055555566fdba in CCharacter::Die (this=0x555555aaa878 <ms_PoolDataCCharacter+936600>, Killer=7, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:2196
#7  0x00005555555d70cd in CPlayer::KillCharacter (this=0x5555558716c0 <ms_PoolDataCPlayer+80640>, Weapon=-3) at src/game/server/player.cpp:1034
#8  0x00005555555d683b in CPlayer::OnDisconnect (this=0x5555558716c0 <ms_PoolDataCPlayer+80640>, pReason=0x7ffff662b030 "", silent=false) at src/game/server/player.cpp:904
#9  0x00005555555f32f2 in CGameContext::OnClientDrop (this=0x7ffff5052010, ClientID=7, pReason=0x7ffff662b030 "", silent=false) at src/game/server/gamecontext.cpp:1794
#10 0x00005555555ac54f in CServer::DelClientCallback (ClientID=7, pReason=0x7ffff662b030 "", pUser=0x7ffff5887010) at src/engine/server/server.cpp:1156
#11 0x0000555555570e40 in CNetServer::Drop (this=0x7ffff65e7e18, ClientID=7, pReason=0x7ffff662b030 "") at src/engine/shared/network_server.cpp:90
#12 0x0000555555570f77 in CNetServer::Update (this=0x7ffff65e7e18) at src/engine/shared/network_server.cpp:106
#13 0x00005555555af706 in CServer::PumpNetwork (this=0x7ffff5887010) at src/engine/server/server.cpp:1840
#14 0x00005555555b09ea in CServer::Run (this=0x7ffff5887010) at src/engine/server/server.cpp:2157
#15 0x00005555555b2d64 in main (argc=1, argv=0x7fffffffe0d8) at src/engine/server/server.cpp:2666
```

**Comment by ChillerDragon** [comment]
```
[19-09-15 20:28:23][chat-command]: 22 used /StockMarket V?*]3eT(b�-OC8GrE3 W<5gBzr#21t)J
[19-09-15 20:28:23][server]: client dropped. cid=10 addr=[0:0:0:0:0:0:0:1]:8216 reason=''
[19-09-15 20:28:23][debug]: character die ID: 10 Name: (8)ChillerDrago
[19-09-15 20:28:23][game]: kill killer='10:(8)ChillerDrago' victim='10:(8)ChillerDrago' weapon=-3 special=0
[19-09-15 20:28:23][chat]: *** '(8)ChillerDrago' has left the game
[19-09-15 20:28:23][game]: leave player='10:(8)ChillerDrago'
[19-09-15 20:28:23][console]: Invalid! Usage: ninjajetpack ?i
[19-09-15 20:28:23][chat-command]: 19 used /ninjajetpack "D4;5(#7RYD!/b?'RK@:&]2FA*GxZiIXMzM  !~{qyOq5XReuO'*Z|4m{*&9cgp_S*�U
[19-09-15 20:28:23][server]: player is ready. ClientID=a addr=[0:0:0:0:0:0:0:1]:8216 secure=yes
[19-09-15 20:28:23][chat-command]: 3 used /pay 0 0 0 YVk*WydmpBn
[19-09-15 20:28:23][chat-command]: 4 used /register Pay i)y ]\c
[19-09-15 20:28:23][chat-command]: 7 used /survival join
[19-09-15 20:28:23][console]: No such command: jail_hammer.
[19-09-15 20:28:23][chat-command]: 17 used /jail_hammer OI[eragon
[19-09-15 20:28:23][emote]: You can now use the preset eye emotes.
[19-09-15 20:28:23][chat-command]: 18 used /eyeemote 7Vre/kLA%7(B8-O2@#].x"V1EH8BU
[19-09-15 20:28:23][console]: Invalid! Usage: 420 vi
[19-09-15 20:28:23][chat-command]: 5 used /420 /|M+HJ{q$D3/#Q6YtK3qc;_]T;OgDpIHa?y$SH.o_?n+t=POmF#UZ:AFj&N
[19-09-15 20:28:23][chat-command]: 6 used /register bl? H*? >N)
[19-09-15 20:28:23][chat-command]: 15 used /spawnweapons JS-%[FN$I�JB\sa.ir&r[,im5OFDfGx=lPR+hr#{.6f }gru3:(
[19-09-15 20:28:23][console]: No such command: /lockwave.
[19-09-15 20:28:23][chat-command]: 16 used //lockwave y#nL%YH'chiller@debian:~/Desktop/git/DDNetPP$ 

[server froze and ctrl-c didn't work so I did ctrl-z]

chiller@debian:~/Desktop/git/DDNetPP$ fg
gdb ./DDNetPP_d
^C^CQuit
(gdb) Quit
(gdb) bt
#0  dbg_break () at src/base/system.c:109
#1  0x00005555555a0200 in dbg_assert_imp (filename=0x555555778818 "src/game/server/entities/drop_pickup.cpp", line=36, test=0, msg=0x55555577880e "wooooooo") at src/base/system.c:103
#2  0x0000555555634e2e in CDropPickup::CDropPickup (this=0x555557b66be0, pGameWorld=0x7ffff50603e0, Type=0, Lifetime=300, Owner=13, Direction=-1, Force=0, ResponsibleTeam=0)
    at src/game/server/entities/drop_pickup.cpp:36
#3  0x0000555555677451 in CCharacter::DropHealth (this=0x555555b55868 <ms_PoolDataCCharacter+1739400>, amount=2) at src/game/server/entities/character.cpp:5662
#4  0x000055555567716a in CCharacter::DropLoot (this=0x555555b55868 <ms_PoolDataCCharacter+1739400>) at src/game/server/entities/character.cpp:5627
#5  0x000055555567b06d in CCharacter::DDPP_DIE (this=0x555555b55868 <ms_PoolDataCCharacter+1739400>, Killer=13, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:6511
#6  0x0000555555665638 in CCharacter::Die (this=0x555555b55868 <ms_PoolDataCCharacter+1739400>, Killer=13, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:2126
#7  0x00005555555d52d8 in CPlayer::KillCharacter (this=0x5555558694c0 <ms_PoolDataCPlayer+149760>, Weapon=-3) at src/game/server/player.cpp:990
#8  0x00005555555d4bec in CPlayer::OnDisconnect (this=0x5555558694c0 <ms_PoolDataCPlayer+149760>, pReason=0x7ffff665dac0 "", silent=false) at src/game/server/player.cpp:875
#9  0x00005555555ee83c in CGameContext::OnClientDrop (this=0x7ffff5052010, ClientID=13, pReason=0x7ffff665dac0 "", silent=false) at src/game/server/gamecontext.cpp:1665
#10 0x00005555555ac53f in CServer::DelClientCallback (ClientID=13, pReason=0x7ffff665dac0 "", pUser=0x7ffff5887010) at src/engine/server/server.cpp:1156
#11 0x0000555555570e30 in CNetServer::Drop (this=0x7ffff65e7e18, ClientID=13, pReason=0x7ffff665dac0 "") at src/engine/shared/network_server.cpp:90
#12 0x0000555555570f67 in CNetServer::Update (this=0x7ffff65e7e18) at src/engine/shared/network_server.cpp:106
#13 0x00005555555af6f6 in CServer::PumpNetwork (this=0x7ffff5887010) at src/engine/server/server.cpp:1840
#14 0x00005555555b09da in CServer::Run (this=0x7ffff5887010) at src/engine/server/server.cpp:2157
#15 0x00005555555b2cfe in main (argc=1, argv=0x7fffffffe0d8) at src/engine/server/server.cpp:2662
(gdb) 
```

**Comment by ChillerDragon** [comment]
```
[19-09-15 20:47:18][debug]: character die ID: 12 Name: (12)ChillerDrag
[19-09-15 20:47:18][game]: kill killer='12:(12)ChillerDrag' victim='12:(12)ChillerDrag' weapon=-3 special=0
[19-09-15 20:47:18][debug]: character die ID: 13 Name: (13)ChillerDrag
[19-09-15 20:47:18][game]: kill killer='13:(13)ChillerDrag' victim='13:(13)ChillerDrag' weapon=-3 special=0
[19-09-15 20:47:18][debug]: character die ID: 15 Name: (15)ChillerDrag
[19-09-15 20:47:18][game]: kill killer='15:(15)ChillerDrag' victim='15:(15)ChillerDrag' weapon=-3 special=0
[19-09-15 20:47:18][debug]: character die ID: 16 Name: (16)ChillerDrag
[19-09-15 20:47:18][game]: kill killer='16:(16)ChillerDrag' victim='16:(16)ChillerDrag' weapon=-3 special=0
[19-09-15 20:47:18][debug]: character die ID: 21 Name: (14)ChillerDrag
[19-09-15 20:47:18][game]: kill killer='21:(14)ChillerDrag' victim='21:(14)ChillerDrag' weapon=-3 special=0
[19-09-15 20:47:18][server]: client dropped. cid=2 addr=[0:0:0:0:0:0:0:1]:16045 reason=''
[19-09-15 20:47:18][debug]: character die ID: 2 Name: (2)ChillerDrago
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][XXXXXXXXXXXXx]: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx
[19-09-15 20:47:18][assert]: src/game/server/entities/drop_pickup.cpp(36): wooooooo

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
dbg_break () at src/base/system.c:109
109		*((volatile unsigned*)0) = 0x0;
(gdb) bt
#0  dbg_break () at src/base/system.c:109
#1  0x00005555555a0200 in dbg_assert_imp (filename=0x555555778818 "src/game/server/entities/drop_pickup.cpp", line=36, test=0, msg=0x55555577880e "wooooooo") at src/base/system.c:103
#2  0x0000555555634e2e in CDropPickup::CDropPickup (this=0x555558500fb0, pGameWorld=0x7ffff50603e0, Type=1, Lifetime=300, Owner=2, Direction=0, Force=0, ResponsibleTeam=0)
    at src/game/server/entities/drop_pickup.cpp:36
#3  0x0000555555677687 in CCharacter::DropArmor (this=0x5555559ee330 <ms_PoolDataCCharacter+267600>, amount=1) at src/game/server/entities/character.cpp:5685
#4  0x0000555555677139 in CCharacter::DropLoot (this=0x5555559ee330 <ms_PoolDataCCharacter+267600>) at src/game/server/entities/character.cpp:5626
#5  0x000055555567b06d in CCharacter::DDPP_DIE (this=0x5555559ee330 <ms_PoolDataCCharacter+267600>, Killer=2, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:6511
#6  0x0000555555665638 in CCharacter::Die (this=0x5555559ee330 <ms_PoolDataCCharacter+267600>, Killer=2, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:2126
#7  0x00005555555d52d8 in CPlayer::KillCharacter (this=0x55555584a5c0 <ms_PoolDataCPlayer+23040>, Weapon=-3) at src/game/server/player.cpp:990
#8  0x00005555555d4bec in CPlayer::OnDisconnect (this=0x55555584a5c0 <ms_PoolDataCPlayer+23040>, pReason=0x7ffff6600cb8 "", silent=false) at src/game/server/player.cpp:875
#9  0x00005555555ee83c in CGameContext::OnClientDrop (this=0x7ffff5052010, ClientID=2, pReason=0x7ffff6600cb8 "", silent=false) at src/game/server/gamecontext.cpp:1665
#10 0x00005555555ac53f in CServer::DelClientCallback (ClientID=2, pReason=0x7ffff6600cb8 "", pUser=0x7ffff5887010) at src/engine/server/server.cpp:1156
#11 0x0000555555570e30 in CNetServer::Drop (this=0x7ffff65e7e18, ClientID=2, pReason=0x7ffff6600cb8 "") at src/engine/shared/network_server.cpp:90
#12 0x0000555555570f67 in CNetServer::Update (this=0x7ffff65e7e18) at src/engine/shared/network_server.cpp:106
#13 0x00005555555af6f6 in CServer::PumpNetwork (this=0x7ffff5887010) at src/engine/server/server.cpp:1840
#14 0x00005555555b09da in CServer::Run (this=0x7ffff5887010) at src/engine/server/server.cpp:2157
#15 0x00005555555b2cfe in main (argc=1, argv=0x7fffffffe0d8) at src/engine/server/server.cpp:2662
(gdb) 
```

**Comment by ChillerDragon** [comment]
```
[19-09-16 12:06:33][chat-command]: 19 used /rankteam Ggbs�kv�+$7j8=@B-w@6@Q>b6@ceZgX,n-L\_8U;9ODAq
[19-09-16 12:06:33][chat-command]: 1 used /survival leave
[19-09-16 12:06:33][chat-command]: 7 used /event h�"�U?/AKW=wV65U6Aqp@knH
[19-09-16 12:06:33][chat-command]: 20 used /survival join
[19-09-16 12:06:33][server]: client dropped. cid=0 addr=[0:0:0:0:0:0:0:1]:8874 reason=''
[19-09-16 12:06:33][debug]: character die ID: 0 Name: ChillerDragon
[19-09-16 12:06:33][assert]: src/game/server/entities/drop_pickup.cpp(20): droppickup playerchar is null

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
dbg_break () at src/base/system.c:109
109		*((volatile unsigned*)0) = 0x0;
(gdb) bt
#0  dbg_break () at src/base/system.c:109
#1  0x00005555555a0200 in dbg_assert_imp (filename=0x5555557787f0 "src/game/server/entities/drop_pickup.cpp", line=20, test=0, msg=0x5555557787d0 "droppickup playerchar is null") at src/base/system.c:103
#2  0x0000555555634cd1 in CDropPickup::CDropPickup (this=0x55555734c8d0, pGameWorld=0x7ffff50603e0, Type=1, Lifetime=300, Owner=0, Direction=-1, Force=1, ResponsibleTeam=0)
    at src/game/server/entities/drop_pickup.cpp:20
#3  0x00005555556774eb in CCharacter::DropArmor (this=0x5555559acde0 <ms_PoolDataCCharacter>, amount=5) at src/game/server/entities/character.cpp:5685
#4  0x0000555555676f9d in CCharacter::DropLoot (this=0x5555559acde0 <ms_PoolDataCCharacter>) at src/game/server/entities/character.cpp:5626
#5  0x000055555567aed1 in CCharacter::DDPP_DIE (this=0x5555559acde0 <ms_PoolDataCCharacter>, Killer=0, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:6511
#6  0x000055555566549c in CCharacter::Die (this=0x5555559acde0 <ms_PoolDataCCharacter>, Killer=0, Weapon=-3, fngscore=false) at src/game/server/entities/character.cpp:2126
#7  0x00005555555d52d8 in CPlayer::KillCharacter (this=0x555555844bc0 <ms_PoolDataCPlayer>, Weapon=-3) at src/game/server/player.cpp:990
#8  0x00005555555d4bec in CPlayer::OnDisconnect (this=0x555555844bc0 <ms_PoolDataCPlayer>, pReason=0x7ffff65efe88 "", silent=false) at src/game/server/player.cpp:875
#9  0x00005555555ee83c in CGameContext::OnClientDrop (this=0x7ffff5052010, ClientID=0, pReason=0x7ffff65efe88 "", silent=false) at src/game/server/gamecontext.cpp:1665
#10 0x00005555555ac53f in CServer::DelClientCallback (ClientID=0, pReason=0x7ffff65efe88 "", pUser=0x7ffff5887010) at src/engine/server/server.cpp:1156
#11 0x0000555555570e30 in CNetServer::Drop (this=0x7ffff65e7e18, ClientID=0, pReason=0x7ffff65efe88 "") at src/engine/shared/network_server.cpp:90
#12 0x0000555555570f67 in CNetServer::Update (this=0x7ffff65e7e18) at src/engine/shared/network_server.cpp:106
#13 0x00005555555af6f6 in CServer::PumpNetwork (this=0x7ffff5887010) at src/engine/server/server.cpp:1840
#14 0x00005555555b09da in CServer::Run (this=0x7ffff5887010) at src/engine/server/server.cpp:2157
#15 0x00005555555b2cfe in main (argc=1, argv=0x7fffffffe0d8) at src/engine/server/server.cpp:2662
(gdb) 
```
