### ISSUE TITLE
Crash in trade command

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#300]
```
[19-09-16 18:35:45][chat-command]: 1 used /a llU 2}[m\)L"/F}?Q 9A~f$\j90waRyR4gSTs26aD  7!}KjlbKgMLuXIhgJ0Gn
[19-09-16 18:35:46][Police]: You are not police.
[19-09-16 18:35:46][chat-command]: 0 used /policechat 0Mj/7/4
[19-09-16 18:35:46][chat-command]: 1 used /mapinfo EKd
[19-09-16 18:35:47][chat-command]: 0 used /survival leave

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
0x00005555556ac40c in CGameContext::ConTr (pResult=0x7fffffff08b0, pUserData=0x7ffff5052010) at src/game/server/ddracechat.cpp:9152
9152			int weapon = pSelf->m_apPlayers[TradeID] ? pSelf->m_apPlayers[TradeID]->m_TradeItem : -1;
(gdb) bt
#0  0x00005555556ac40c in CGameContext::ConTr (pResult=0x7fffffff08b0, pUserData=0x7ffff5052010) at src/game/server/ddracechat.cpp:9152
#1  0x0000555555584990 in CConsole::ExecuteLineStroked (this=0x555556a26860, Stroke=1, pStr=0x7ffff6a20ac6 "tr A9-We!Q12: rsE1&'fD4HD+OZyO/Q{ ()-1kWE\302Lu\247:OE{R4>hqr&h'x\302Iwk", ClientID=1)
    at src/engine/shared/console.cpp:419
#2  0x0000555555584c17 in CConsole::ExecuteLine (this=0x555556a26860, pStr=0x7ffff6a20ac6 "tr A9-We!Q12: rsE1&'fD4HD+OZyO/Q{ ()-1kWE\302Lu\247:OE{R4>hqr&h'x\302Iwk", ClientID=1)
    at src/engine/shared/console.cpp:472
#3  0x0000555555600dba in CGameContext::OnMessage (this=0x7ffff5052010, MsgID=17, pUnpacker=0x7fffffffd360, ClientID=1) at src/game/server/gamecontext.cpp:7341
#4  0x00005555555aed98 in CServer::ProcessClientPacket (this=0x7ffff5887010, pPacket=0x7fffffffdd60) at src/engine/server/server.cpp:1675
#5  0x00005555555af83e in CServer::PumpNetwork (this=0x7ffff5887010) at src/engine/server/server.cpp:1863
#6  0x00005555555b09da in CServer::Run (this=0x7ffff5887010) at src/engine/server/server.cpp:2157
#7  0x00005555555b2cfe in main (argc=1, argv=0x7fffffffe0d8) at src/engine/server/server.cpp:2662
(gdb) 
```

**Comment by ChillerDragon** [comment]
```
[19-09-16 18:40:42][console]: No such command: S?p~'p6EvHq('Y2L0I4yCc.
[19-09-16 18:40:42][chat-command]: 10 used /rainbow KfNYr6H>kbSsL7l73W9C>YF;S?p~'p6EvHq('Y2L0I4yCc;
[19-09-16 18:40:42][chat-command]: 11 used /mapsave z@G\[%/]C Ai�/K
[19-09-16 18:40:42][chat-command]: 17 used /survival join

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
0x00005555556ac40c in CGameContext::ConTr (pResult=0x7fffffff08b0, pUserData=0x7ffff5052010) at src/game/server/ddracechat.cpp:9152
9152			int weapon = pSelf->m_apPlayers[TradeID] ? pSelf->m_apPlayers[TradeID]->m_TradeItem : -1;
(gdb) bt
#0  0x00005555556ac40c in CGameContext::ConTr (pResult=0x7fffffff08b0, pUserData=0x7ffff5052010) at src/game/server/ddracechat.cpp:9152
#1  0x0000555555584990 in CConsole::ExecuteLineStroked (this=0x555556a26860, Stroke=1, pStr=0x7ffff6a20ac6 "tr )1v}Z(\\xZY6\"\247'\"+)OzYc;x\247UuzCk$)-2_/j&}\247\062!6vG2u28'>T", ClientID=13)
    at src/engine/shared/console.cpp:419
#2  0x0000555555584c17 in CConsole::ExecuteLine (this=0x555556a26860, pStr=0x7ffff6a20ac6 "tr )1v}Z(\\xZY6\"\247'\"+)OzYc;x\247UuzCk$)-2_/j&}\247\062!6vG2u28'>T", ClientID=13)
    at src/engine/shared/console.cpp:472
#3  0x0000555555600dba in CGameContext::OnMessage (this=0x7ffff5052010, MsgID=17, pUnpacker=0x7fffffffd360, ClientID=13) at src/game/server/gamecontext.cpp:7341
#4  0x00005555555aed98 in CServer::ProcessClientPacket (this=0x7ffff5887010, pPacket=0x7fffffffdd60) at src/engine/server/server.cpp:1675
#5  0x00005555555af83e in CServer::PumpNetwork (this=0x7ffff5887010) at src/engine/server/server.cpp:1863
#6  0x00005555555b09da in CServer::Run (this=0x7ffff5887010) at src/engine/server/server.cpp:2157
#7  0x00005555555b2cfe in main (argc=1, argv=0x7fffffffe0d8) at src/engine/server/server.cpp:2662
(gdb) 
```

**Comment by ChillerDragon** [comment]
```
[19-09-16 18:43:07][chat-command]: 3 used /register pentest_20 123 123
[19-09-16 18:43:07][chat-command]: 0 used /rainbow D&O6Gi%,L\/#&!_K:u2KZM_+~rPks]&W<mPU0mIyzir/fp$A&y_x/'TyS+J�b
[19-09-16 18:43:07][chat-command]: 7 used /hide P#%QTb1;UcQ_tso-?F='�\=7XXE_k",0:3D$5,3Mvb%=0.6DXJ2
[19-09-16 18:43:07][chat-command]: 12 used /login pentest_17 123 123
[19-09-16 18:43:07][chat-command]: 10 used /login pentest_10 123 123
[19-09-16 18:43:07][chat-command]: 1 used /register pentest_17 123 123

Thread 1 "DDNetPP_d" received signal SIGSEGV, Segmentation fault.
0x00005555556ac40c in CGameContext::ConTr (pResult=0x7fffffff08b0, pUserData=0x7ffff5052010) at src/game/server/ddracechat.cpp:9152
9152			int weapon = pSelf->m_apPlayers[TradeID] ? pSelf->m_apPlayers[TradeID]->m_TradeItem : -1;
(gdb) bt
#0  0x00005555556ac40c in CGameContext::ConTr (pResult=0x7fffffff08b0, pUserData=0x7ffff5052010) at src/game/server/ddracechat.cpp:9152
#1  0x0000555555584990 in CConsole::ExecuteLineStroked (this=0x555556a26860, Stroke=1, pStr=0x7ffff6a20ac6 "tr LuZ%GM", ClientID=6) at src/engine/shared/console.cpp:419
#2  0x0000555555584c17 in CConsole::ExecuteLine (this=0x555556a26860, pStr=0x7ffff6a20ac6 "tr LuZ%GM", ClientID=6) at src/engine/shared/console.cpp:472
#3  0x0000555555600dba in CGameContext::OnMessage (this=0x7ffff5052010, MsgID=17, pUnpacker=0x7fffffffd360, ClientID=6) at src/game/server/gamecontext.cpp:7341
#4  0x00005555555aed98 in CServer::ProcessClientPacket (this=0x7ffff5887010, pPacket=0x7fffffffdd60) at src/engine/server/server.cpp:1675
#5  0x00005555555af83e in CServer::PumpNetwork (this=0x7ffff5887010) at src/engine/server/server.cpp:1863
#6  0x00005555555b09da in CServer::Run (this=0x7ffff5887010) at src/engine/server/server.cpp:2157
#7  0x00005555555b2cfe in main (argc=1, argv=0x7fffffffe0d8) at src/engine/server/server.cpp:2662
(gdb) 
```
