### ISSUE TITLE
crash: jail open

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#308]
```
[21-06-24 13:57:05][chat-command]: 2 used /jail_code 5years idiot
[21-06-24 13:57:17][chat]: 3:-2:5years: ещё

Thread 1 "BlmapChill_d" received signal SIGSEGV, Segmentation fault.
CGameContext::ConJail (pResult=0x7ffffffefe00, pUserData=0x7ffff4b5a010) at /home/chiller/git/DDNetPP/src/game/server/ddracechat.cpp:7240
7240                    if (!pSelf->m_apPlayers[jailedID]->m_JailTime)
(gdb) bt
#0  CGameContext::ConJail (pResult=0x7ffffffefe00, pUserData=0x7ffff4b5a010) at /home/chiller/git/DDNetPP/src/game/server/ddracechat.cpp:7240
#1  0x0000555555744ba7 in CConsole::ExecuteLineStroked (this=0x555556a4eac0, Stroke=1, pStr=0x7ffff6528ac6 "jail open ybil 4ela 5years", ClientID=2) at /home/chiller/git/DDNetPP/src/engine/shared/console.cpp:419
#2  0x0000555555744e9e in CConsole::ExecuteLine (this=0x555556a4eac0, pStr=0x7ffff6528ac6 "jail open ybil 4ela 5years", ClientID=2) at /home/chiller/git/DDNetPP/src/engine/shared/console.cpp:472
#3  0x000055555563d07c in CGameContext::OnMessage (this=0x7ffff4b5a010, MsgID=17, pUnpacker=0x7fffffffb070, ClientID=2) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:7382
#4  0x0000555555571bbb in CServer::ProcessClientPacket (this=0x7ffff538f010, pPacket=0x7fffffffcca0) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:1675
#5  0x00005555555727a5 in CServer::PumpNetwork (this=0x7ffff538f010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:1863
#6  0x0000555555573ad8 in CServer::Run (this=0x7ffff538f010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2157
#7  0x0000555555576360 in main (argc=2, argv=0x7fffffffd938) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2662
(gdb) print pSelf->m_apPlayers[jailedID]
$1 = (CPlayer *) 0x400000020
(gdb) print pSelf->m_apPlayers[jailedID]->m_JailTime
Cannot access memory at address 0x4000026c8
(gdb) 
```

**Comment by Anime-pdf** [comment]
ещё
