### ISSUE TITLE
pChr is null on ChillBlock5

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#330]
```
Thread 1 "chillblock_d" received signal SIGSEGV, Segmentation fault.
0x00005555556e1436 in CCharacter::DummyTick (this=0x5555559598e0 <gs_PoolDataCCharacter+273216>)
    at /home/chiller/git/DDNetPP/src/game/server/entities/character_dummymodes.cpp:7574
7574                                                                    if(pChr->m_FreezeTime > 0 && pChr->m_Pos.y > 208 * 32 && !pChr->isFreezed) //wenn der Gegner tief und freeze is macht es wenig sinn den frei zu hammern
(gdb) print pChr
$1 = (CCharacter *) 0x0
```

**Comment by ChillerDragon** [comment]
```
Thread 1 "chillblock_d" received signal SIGSEGV, Segmentation fault.
0x00005555556e1312 in CCharacter::DummyTick (this=0x555555938340 <gs_PoolDataCCharacter+136608>) at /home/chiller/git/DDNetPP/src/game/server/entities/character_dummymodes.cpp:7539
7539                                                                            if(m_Core.m_Pos.y < pChr->m_Pos.y) //wenn der bot über dem spieler is soll er hooken
(gdb) bt
#0  0x00005555556e1312 in CCharacter::DummyTick (this=0x555555938340 <gs_PoolDataCCharacter+136608>) at /home/chiller/git/DDNetPP/src/game/server/entities/character_dummymodes.cpp:7539
#1  0x00005555556b7b6b in CCharacter::DDPP_Tick (this=0x555555938340 <gs_PoolDataCCharacter+136608>) at /home/chiller/git/DDNetPP/src/game/server/entities/character_ddpp.cpp:967
#2  0x00005555556a5935 in CCharacter::Tick (this=0x555555938340 <gs_PoolDataCCharacter+136608>) at /home/chiller/git/DDNetPP/src/game/server/entities/character.cpp:846
#3  0x000055555576ed95 in CGameWorld::Tick (this=0x7ffff432aab8) at /home/chiller/git/DDNetPP/src/game/server/gameworld.cpp:272
#4  0x0000555555711801 in CGameContext::OnTick (this=0x7ffff431a010) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:897
#5  0x0000555555641ed7 in CServer::Run (this=0x7ffff6356010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2694
#6  0x00005555556478e4 in main (argc=2, argv=0x7fffffffd148) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:3781
(gdb) p pChr
$1 = (CCharacter *) 0x0
```
