### ISSUE TITLE
Crash in libcurl SIGPIPE Broken pipe

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#346]
```
[2022-07-18 18:51:17][register/7/ipv4]: ERROR: the master server reports that clients can not connect to this server.
[2022-07-18 18:51:17][register/7/ipv4]: ERROR: configure your firewall/nat to let through udp on port 8303.
[2022-07-18 18:51:17][register/7/ipv4]: registering...
[New Thread 0x7fffe5b72700 (LWP 3463467)]
[Thread 0x7fffe5b72700 (LWP 3463467) exited]
[2022-07-18 19:04:58][register/7/ipv6]: registering...
[2022-07-18 19:05:13][register/7/ipv6]: registering...
[2022-07-18 19:05:56][register/6/ipv4]: registering...
[2022-07-18 19:05:58][register/7/ipv6]: registering...
[2022-07-18 19:06:00][http]: https://master1.ddnet.tw/ddnet/15/register failed. libcurl error: Operation too slow. Less than 500 bytes/sec transferred the last 5 seconds
[2022-07-18 19:06:00][register/6/ipv6]: error response from master
[2022-07-18 19:06:12][register/6/ipv4]: registering...
[2022-07-18 19:06:14][register/7/ipv6]: registering...
[2022-07-18 19:09:22][chat]: *** [INFO] Try the commad '/quest' to play some quests.
[New Thread 0x7fffe5b72700 (LWP 3463824)]
[Thread 0x7fffe5b72700 (LWP 3463824) exited]

Thread 5 "chillblock_d" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7ffff0d59700 (LWP 3365564)]
__libc_write (nbytes=24, buf=0x629001626203, fd=14) at ../sysdeps/unix/sysv/linux/write.c:26
26      ../sysdeps/unix/sysv/linux/write.c: No such file or directory.
(gdb) bt
#0  __libc_write (nbytes=24, buf=0x629001626203, fd=14) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __libc_write (fd=14, buf=0x629001626203, nbytes=24) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x000000000044aa90 in write ()
#3  0x00007ffff7d8b5c5 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007ffff7d8672a in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#5  0x00007ffff7d85784 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007ffff7d85c43 in BIO_write () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007ffff747f91a in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007ffff7480809 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007ffff748a1da in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007ffff7488425 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x00007ffff7c95492 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#12 0x00007ffff7c954f1 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#13 0x00007ffff7c9bb8b in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#14 0x00007ffff7c51f4a in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#15 0x00007ffff7c70090 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#16 0x00007ffff7c71404 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#17 0x00007ffff7c71c06 in curl_multi_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#18 0x00007ffff7c48943 in curl_easy_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#19 0x000000000157f65e in CHttpRequest::RunImpl (this=0x61b0000df280, pUser=0x6230002fcd00) at /home/chiller/git/DDNetPP/src/engine/shared/http.cpp:257
#20 0x000000000157d4f5 in CHttpRequest::Run (this=0x61b0000df280) at /home/chiller/git/DDNetPP/src/engine/shared/http.cpp:154
#21 0x00000000015992ae in CJobPool::RunBlocking (pJob=0x61b0000df280) at /home/chiller/git/DDNetPP/src/engine/shared/jobs.cpp:118
#22 0x0000000001569e8a in IEngine::RunJobBlocking (pJob=0x61b0000df280) at /home/chiller/git/DDNetPP/src/engine/shared/engine.cpp:118
#23 0x000000000051a51b in CRegister::CProtocol::CJob::Run (this=0x608000102c30) at /home/chiller/git/DDNetPP/src/engine/server/register.cpp:414
#24 0x00000000015992ae in CJobPool::RunBlocking (pJob=0x608000102c30) at /home/chiller/git/DDNetPP/src/engine/shared/jobs.cpp:118
#25 0x0000000001598f25 in CJobPool::WorkerThread (pUser=0x617000000410) at /home/chiller/git/DDNetPP/src/engine/shared/jobs.cpp:73
#26 0x000000000169e406 in thread_run (user=0x602000004c30) at /home/chiller/git/DDNetPP/src/base/system.cpp:723
#27 0x00007ffff7793ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#28 0x00007ffff76a3def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by ChillerDragon** [comment]
closed via https://github.com/DDNetPP/server/commit/636dd5b56b0ac2e3b68a2f89e47691e48fd7caa9

**Comment by TeeFifnik** [comment]
[2024-09-15 23:30:18][register/6/ipv4]: registering...
[2024-09-15 23:30:18][engine]: job added
[2024-09-15 23:30:18][register/7/ipv4]: registering...
[2024-09-15 23:30:18][engine]: job added
[2024-09-15 23:30:18][http]: https://master1.ddnet.tw/ddnet/15/register failed. libcurl error: The requested URL returned error: 405
[2024-09-15 23:30:18][register/6/ipv4]: error response from master
[2024-09-15 23:30:18][http]: https://master1.ddnet.tw/ddnet/15/register failed. libcurl error: The requested URL returned error: 405
[2024-09-15 23:30:18][register/7/ipv4]: error response from master

**Comment by ChillerDragon** [comment]
@TeeFifnik this is unrelated to this issue. Could you open a new issue with more details about your setup? Which DDNet++ version are you using?

**Comment by fokkonaut** [comment]
Use ddnet.org instead of ddnet.tw

**Comment by ChillerDragon** [comment]
ah good catch @fokkonaut yes that means updating the server. I think the latest release is too old for that ._.
