### ISSUE TITLE
Client segfaults on launch

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#350]
```
2023-02-18 08:44:33 I console: executing 'autoexec.cfg'

Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
CChat::AddLine (this=0x7fffe7473c68, ClientID=-2, Team=0, pLine=0x7ffffffea386 'x' <repeats 21 times>) at /home/chiller/Desktop/git/DDNetPP/src/game/client/components/chat.cpp:759
759                     Graphics()->DeleteQuadContainer(pCurrentLine->m_QuadContainerIndex);
(gdb) bt
#0  CChat::AddLine(int, int, char const*) (this=0x7fffe7473c68, ClientID=-2, Team=0, pLine=0x7ffffffea386 'x' <repeats 21 times>) at /home/chiller/Desktop/git/DDNetPP/src/game/client/components/chat.cpp:759
#1  0x0000555555735fbc in CChat::Echo(char const*) (this=0x7fffe7473c68, pString=0x7ffffffea386 'x' <repeats 21 times>) at /home/chiller/Desktop/git/DDNetPP/src/game/client/components/chat.cpp:150
#2  0x0000555555735f0b in CChat::ConEcho(IConsole::IResult*, void*) (pResult=0x7ffffffea370, pUserData=0x7fffe7473c68) at /home/chiller/Desktop/git/DDNetPP/src/game/client/components/chat.cpp:139
#3  0x000055555592f1d9 in CConsole::ExecuteLineStroked(int, char const*, int, bool)
    (this=0x555555d0ab60, Stroke=1, pStr=0x7fffffff456f "echo \"", 'x' <repeats 21 times>, "\"", ClientID=-1, InterpretSemicolons=true) at /home/chiller/Desktop/git/DDNetPP/src/engine/shared/console.cpp:541
#4  0x000055555592f52c in CConsole::ExecuteLine(char const*, int, bool) (this=0x555555d0ab60, pStr=0x7fffffff456f "echo \"", 'x' <repeats 21 times>, "\"", ClientID=-1, InterpretSemicolons=true)
    at /home/chiller/Desktop/git/DDNetPP/src/engine/shared/console.cpp:605
#5  0x000055555592f815 in CConsole::ExecuteFile(char const*, int, bool, int) (this=0x555555d0ab60, pFilename=0x555555a8abf6 "autoexec.cfg", ClientID=-1, LogFailure=false, StorageType=-1)
    at /home/chiller/Desktop/git/DDNetPP/src/engine/shared/console.cpp:648
#6  0x00005555556a267a in main(int, char const**) (argc=1, argv=0x7fffffffca38) at /home/chiller/Desktop/git/DDNetPP/src/engine/client/client.cpp:4664
```

My autoexec.cfg contains a bunch of ``echo`` commands maybe thats causing it. This is a server only project but still the client should not crash. Maybe its a upstream bug but doubt. Investigate this some time.

**Comment by ChillerDragon** [comment]
sänks robster. Issue moved to upstream :)
