### ISSUE TITLE
spookyghost crash

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#361]
```
2023-07-08 16:06:12 I debug: character die ID: 0 Name: flappy.*

Thread 1 "blmapchill_d" received signal SIGSEGV, Segmentation fault.
CGameContext::SendEmoticon (this=0x7ffff4158010, ClientID=3, Emoticon=7, TargetClientID=0) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:647
647             if(m_apPlayers[ClientID]->m_SpookyGhostActive)
(gdb) bt
#0  CGameContext::SendEmoticon (this=0x7ffff4158010, ClientID=3, Emoticon=7, TargetClientID=0) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:647
#1  0x000055555569797c in CGameContext::OnMessage (this=0x7ffff4158010, MsgID=23, pUnpacker=0x7fffffffabb0, ClientID=3) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2717
#2  0x00005555555b415e in CServer::ProcessClientPacket (this=0x7ffff51a0010, pPacket=0x7fffffffbe50) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:1869
#3  0x00005555555b692f in CServer::PumpNetwork (this=0x7ffff51a0010, PacketWaiting=true) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2494
#4  0x00005555555b8957 in CServer::Run (this=0x7ffff51a0010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2921
#5  0x000055555559e4bc in main (argc=2, argv=0x7fffffffd208) at /home/chiller/git/DDNetPP/src/engine/server/main.cpp:191
```

**Comment by ChillerDragon** [comment]
This line now says

```C++
	if(pPlayer && pPlayer->m_SpookyGhostActive)
```

So that seems fixed.
