### ISSUE TITLE
Crash in emote

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#363]
```
2023-08-21 13:33:24 I debug: character die ID: 0 Name: flappy.*

Thread 1 "blmapchill_d" received signal SIGSEGV, Segmentation fault.
CGameContext::SendEmoticon (this=0x7ffff414b010, ClientID=2, Emoticon=14, TargetClientID=0) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:647
warning: Source file is more recent than executable.
647     void CGameContext::SendEmoticon(int ClientID, int Emoticon, int TargetClientID)
(gdb) bt
#0  CGameContext::SendEmoticon (this=0x7ffff414b010, ClientID=2, Emoticon=14, TargetClientID=0) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:647
#1  0x00005555556979b8 in CGameContext::OnMessage (this=0x7ffff414b010, MsgID=23, pUnpacker=0x7fffffffabb0, ClientID=2) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2709
#2  0x00005555555b4512 in CServer::ProcessClientPacket (this=0x7ffff51a0010, pPacket=0x7fffffffbe50) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:1869
#3  0x00005555555b6ce3 in CServer::PumpNetwork (this=0x7ffff51a0010, PacketWaiting=true) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2494
#4  0x00005555555b8d0d in CServer::Run (this=0x7ffff51a0010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2921
#5  0x000055555559e86c in main (argc=2, argv=0x7fffffffd208) at /home/chiller/git/DDNetPP/src/engine/server/main.cpp:191
```

899392823b8392be07f4652e3b9a147b52e463d0

**Comment by ChillerDragon** [comment]
should be closed by 13f81ceeb49911d57a4001c3513a210180ba03a6
there is no unsafe code left in that function
