### ISSUE TITLE
Segfault weapon reset

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/DDNetPP#367]
```
2024-01-26 13:33:56 I teamchat: 1:4:Chillingo.*: Welcome to the shop, Paweł jumper! Press f4 to start shopping.
2024-01-26 13:33:57 I teamchat: 1:4:Chillingo.*: Welcome to the shop, menda! Press f4 to start shopping.
2024-01-26 13:33:58 I debug: character die ID: 0 Name: flappy.*

Thread 1 "blmapchill_d" received signal SIGSEGV, Segmentation fault.
0x000055555561c255 in CCharacter::DropWeapon (this=0x555555a81b60 <gs_PoolDataCCharacter+17088>,
    WeaponID=0) at /home/chiller/git/DDNetPP/src/game/server/entities/character_ddpp.cpp:773
773                             pWeapon->Reset();
(gdb) bt
#0  0x000055555561c255 in CCharacter::DropWeapon (this=0x555555a81b60 <gs_PoolDataCCharacter+17088>, WeaponID=0) at /home/chiller/git/DDNetPP/src/game/server/entities/character_ddpp.cpp:773
#1  0x00005555556bbb13 in CGameContext::VotedNo (this=0x7ffff412e010, pChr=0x555555a81b60 <gs_PoolDataCCharacter+17088>) at /home/chiller/git/DDNetPP/src/game/server/gamecontext_votes.cpp:45
#2  0x0000555555679c52 in CGameContext::OnVoteNetMessage (this=0x7ffff412e010, pMsg=0x555555ad6da0 <CGameContext::PreProcessMsg(int*, CUnpacker*, int)::s_aRawMsg>, ClientID=3)
    at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2542
#3  0x0000555555677903 in CGameContext::OnMessage (this=0x7ffff412e010, MsgID=24, pUnpacker=0x7fffffff9f10, ClientID=3) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2122
#4  0x00005555555abb9d in CServer::ProcessClientPacket (this=0x7ffff518b010, pPacket=0x7fffffffb9f0) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:1978
#5  0x00005555555ae031 in CServer::PumpNetwork (this=0x7ffff518b010, PacketWaiting=true) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2607
#6  0x00005555555b0334 in CServer::Run (this=0x7ffff518b010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:3074
#7  0x00005555555977a6 in main (argc=2, argv=0x7fffffffcda8) at /home/chiller/git/DDNetPP/src/engine/server/main.cpp:193

[*] commit: 23e6657603c4ffa4c48ae7f947ace472c714f21e
```

23e6657603c4ffa4c48ae7f947ace472c714f21e

**Comment by ChillerDragon** [comment]
```
2024-03-14 13:45:03 I debug: character die ID: 3 Name: MLG_PRO.*

Thread 1 "chillblock_d" received signal SIGSEGV, Segmentation fault.
0x000055555561c255 in CCharacter::DropWeapon (this=0x555555a87460 <gs_PoolDataCCharacter+39872>, WeaponID=3) at /home/chiller/git/DDNetPP/src/game/server/entities/character_ddpp.cpp:773
773                             pWeapon->Reset();
(gdb) bt
#0  0x000055555561c255 in CCharacter::DropWeapon (this=0x555555a87460 <gs_PoolDataCCharacter+39872>, WeaponID=3) at /home/chiller/git/DDNetPP/src/game/server/entities/character_ddpp.cpp:773
#1  0x00005555556bbb13 in CGameContext::VotedNo (this=0x7ffff412e010, pChr=0x555555a87460 <gs_PoolDataCCharacter+39872>) at /home/chiller/git/DDNetPP/src/game/server/gamecontext_votes.cpp:45
#2  0x0000555555679c52 in CGameContext::OnVoteNetMessage (this=0x7ffff412e010, pMsg=0x7ffff4132d90, ClientID=7) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2542
#3  0x0000555555677903 in CGameContext::OnMessage (this=0x7ffff412e010, MsgID=24, pUnpacker=0x7fffffff9f80, ClientID=7) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2122
#4  0x00005555555abb9d in CServer::ProcessClientPacket (this=0x7ffff518b010, pPacket=0x7fffffffba60) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:1978
#5  0x00005555555ae031 in CServer::PumpNetwork (this=0x7ffff518b010, PacketWaiting=true) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2607
#6  0x00005555555b0334 in CServer::Run (BFD: reopening /usr/lib/debug/.build-id/04/01bd8da6edab3e45399d62571357ab12545133.debug: No such file or directory
warning: Can't read data for section '.debug_loclists' in file '/usr/lib/debug/.build-id/04/01bd8da6edab3e45399d62571357ab12545133.debug'
this=0x7ffff518b010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:3074
#7  0x00005555555977a6 in main (argc=2, argv=0x7fffffffce18) at /home/chiller/git/DDNetPP/src/engine/server/main.cpp:193
```

72aa916964f4c1714463314ea9b6b5e894fda807

**Comment by ChillerDragon** [comment]
```
2024-02-25 00:03:38 I debug: character die ID: 0 Name: flappy.*

Thread 1 "blmapchill_d" received signal SIGSEGV, Segmentation fault.
0x000055555561c053 in CCharacter::DropWeapon (this=0x555555a81b60 <gs_PoolDataCCharacter+17088>, WeaponID=3) at /home/chiller/git/DDNetPP/src/game/server/entities/character_ddpp.cpp:773
773                             pWeapon->Reset();
(gdb) bt
#0  0x000055555561c053 in CCharacter::DropWeapon (this=0x555555a81b60 <gs_PoolDataCCharacter+17088>, WeaponID=3) at /home/chiller/git/DDNetPP/src/game/server/entities/character_ddpp.cpp:773
#1  0x00005555556bb7d1 in CGameContext::VotedNo (this=0x7ffff412e010, pChr=0x555555a81b60 <gs_PoolDataCCharacter+17088>) at /home/chiller/git/DDNetPP/src/game/server/gamecontext_votes.cpp:45
#2  0x0000555555679910 in CGameContext::OnVoteNetMessage (this=0x7ffff412e010, pMsg=0x555555ad6da0 <CGameContext::PreProcessMsg(int*, CUnpacker*, int)::s_aRawMsg>, ClientID=3)
    at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2542
#3  0x00005555556775c1 in CGameContext::OnMessage (this=0x7ffff412e010, MsgID=24, pUnpacker=0x7fffffff9f20, ClientID=3) at /home/chiller/git/DDNetPP/src/game/server/gamecontext.cpp:2122
#4  0x00005555555abc33 in CServer::ProcessClientPacket (this=0x7ffff518b010, pPacket=0x7fffffffba00) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:1978
#5  0x00005555555ae0c7 in CServer::PumpNetwork (this=0x7ffff518b010, PacketWaiting=true) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:2607
#6  0x00005555555b03ca in CServer::Run (BFD: reopening /usr/lib/debug/.build-id/04/01bd8da6edab3e45399d62571357ab12545133.debug: No such file or directory
warning: Can't read data for section '.debug_loclists' in file '/usr/lib/debug/.build-id/04/01bd8da6edab3e45399d62571357ab12545133.debug'
this=0x7ffff518b010) at /home/chiller/git/DDNetPP/src/engine/server/server.cpp:3074
#7  0x0000555555597826 in main (argc=2, argv=0x7fffffffcdb8) at /home/chiller/git/DDNetPP/src/engine/server/main.cpp:193
```

72aa916964f4c1714463314ea9b6b5e894fda807
